const contractAddress = "0x875cdE6e2620146F9F4F54C1b6280eD4Fa11D110"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Unknown Crew NFT Project!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'Unknown Crew NFT Project is a Free Mint NFT collection of cadets and officers that is inspired by famous sci-fi tv series like Star Trek and The Orville. This collection was created to celebrate the official launch of the Unknown Universe Academy Discord Server. You can mint for free but you would need to bare the gas fee. These NFTs are collectibles and you can do what ever you want with it. For further clarification, please join our Discord server.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
